### ISSUE TITLE
error: class "GlobalSettings" has no member "getInstance"

### ISSUE THREAD

**Issue by Heraclius** [chrxh/alien#105]
I have no idea why this would be, but when I pulled the most recent version and tried to compile it I got this compilation error:

```
.../alien/source/EngineGpuKernels/DataAccessKernelsLauncher.cu(65): error: class "GlobalSettings" has no member "getInstance"
```

So yeah... Basically the problem was in the Macros.cuh file. The actual method name is simply `get()`

**Comment by Gardene-el** [comment]
This issue is caused by [commit: use singleton macro wherever possible](https://github.com/chrxh/alien/commit/45f83c8f548b9a8f1f699bd4ebf87bfbdbd47aa4). I think it is a tiny oversight, you can fix it by changing all `GlobalSettings::getInstance()`(line 76, line 86, line 95) in `source/EngineGpuKernels/Macros.cuh` into `GlobalSettings::get()`.

**Comment by chrxh** [comment]
I forgot to commit some changes. It's corrected now.
