### ISSUE TITLE
Can't start app, gives MSVCP140_.dll was not found error

### ISSUE THREAD

**Issue by etapic** [chrxh/alien#35]
After installed from latest installer on window 10  app failing to start, getting error: The code execution cannot proceed because MSVCP140_.dll was not found.

**Comment by chrxh** [comment]
MSVCP140_.dll is part of the "Microsoft Visual C++ Redistributable Packages" and will automatically be installed (since it is preselected in the installer).
Did you deselect this item in the installer?
If so, you can run the installer again or install it manually by running `vcredist_x64.exe` in the bin folder.

**Comment by etapic** [comment]
ok reinstall helped
