### ISSUE TITLE
Token can't jump as expect

### ISSUE THREAD

**Issue by RayAdas-GA-17** [chrxh/alien#51]
![image](https://user-images.githubusercontent.com/71073838/184467832-e5e1b8d9-2ae6-45ac-b84a-b53979adab24.png)
I create a cluster like the image. The three cells on the top can work normally that token can jump from 0, 1 to 2. The cell 2 is a computation so I use "mov BRANCH_NUMBER, 5" to make sure that the token can jump to cell 0. So the token can circle in these three cells, and it can form another token when passing through the cell 1.
The new token can jump from cell 1 to cell 2(at the middle of the cluster). 
But it can't always jump from cell 2 to the two cell 3 as expect. It may disappear.
Is this phenomenon normal? How can I make it jump from cell 2 to cell 3?

**Comment by RayAdas-GA-17** [comment]
Here are two images that can show the problem.
![Q3{UAOAE@`D~5{W$MA J9E](https://user-images.githubusercontent.com/71073838/184468966-57747108-707e-4be4-b8b3-e18ff3327a88.png)
![712@7Q`OBSGZ88`@{734BW7](https://user-images.githubusercontent.com/71073838/184468970-d3876361-2535-4c3c-95ab-cbc58b8c780e.png)

**Comment by chrxh** [comment]
Hi,
This is because the tokens have an energy value and (like the cells) decay when it falls below a critical value. During forking, the energy of the tokens is also split. This can cause the energy value of the two successor tokens to fall below the critical threshold. Unfortunately, this fact is not documented yet.

In your case you can do 2 things:
- You can program the tokens to pump energy from the cells. This can be done in a cell program with `mov ENERGY_GUIDANCE_IN, ENERGY_GUIDANCE_IN::HARVEST_CELL`. Or alternatively set the value 4 in the token memory at address 1.
- There is also the possibility to set the critical energy value of a token to 0. This can't be set via the gui at the moment. You have to open the *.settings.json file of the simulation with an editor and change the entry in the node "simulation parameters" ->"token" -> "min energy" from 3.0 to 0.0.

Please let me know if it works in your case.

**Comment by RayAdas-GA-17** [comment]
Thanks for your reply.
I tried the two methods you mentioned, and they both worked.
Thanks again for your help.
