### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by joshuajon** [chrxh/alien#78]
The documentation frequently references examples in the ./examples/ directory, but I can't find them anywhere!  Do these exist and if so where can they be acquired?

Thanks!

**Comment by TheBarret** [comment]
> The documentation frequently references examples in the ./examples/ directory, but I can't find them anywhere! Do these exist and if so where can they be acquired?
> 
> Thanks!

In the simulator is a browser where everyone can browse and upload his genomes and simulations,

![image](https://github.com/chrxh/alien/assets/25234371/414fbfd7-0184-4e0b-a1b4-ac20e98eea93)

![image](https://github.com/chrxh/alien/assets/25234371/83db8503-929d-44c5-b924-01ae8175066f)

**Comment by joshuajon** [comment]
The browser seems great, but the docs reference files like "./examples/simulations/Complex Fluids.sim". for example here: https://alien-project.gitbook.io/docs/getting-started/simulation-parameters

Maybe those files exist within the browser somewhere?  If so, then this is just a documentation issue.

**Comment by rocketjoe123** [comment]
If you look at the beginning of each page there’s a bit about how the documentation was written for an earlier version of the simulation. This is most likely where the discrepancies you’re encountering originate, as the Examples folder has been removed in favor of simulations uploaded to the built in browser. At least as far as I’m aware, chrxh would obviously know the exact current state of things better than I do.

**Comment by TheBarret** [comment]
> The browser seems great, but the docs reference files like "./examples/simulations/Complex Fluids.sim". for example here: https://alien-project.gitbook.io/docs/getting-started/simulation-parameters
> 
> Maybe those files exist within the browser somewhere? If so, then this is just a documentation issue.

You can try my supplementary how-to, it is a quick version of "what and how"

https://github.com/chrxh/alien/discussions/72

**Comment by chrxh** [comment]
The documentation was written for the previous ALIEN version. Thus everything written there is potentially outdated. This is the reason why I had added a warning on the top of each page.

There are now no more sim files in the repository (except the startup example).  Everything can be found in the in-game browser. This step was taken mainly for 2 reasons:
- It much more easier to handle, load and organize simulations. In particular feedback can be given via reactions.
- It could be problematic to store lots of binary files in Git. It is possible to mitigate the problem somewhat by using Git LFS, which I do, but it is still not the best solution. 

A disadvantage is that the simulation files are now on a database on a server. Although everyone can save them locally, but if the server is not reachable, one can not access them anymore. For this reason, I will put all simulations in a separate repository on GitHub in the future. That should compensate this disadvantage.

Regarding the documentation of the current version:
Writing documentation is important but no fun, especially if you enjoy developing. It took me a lot of effort to do that in the past. That's why I'm following a different concept for the current version: The essential information should already be contained in the program help and in the countless tooltips.

**Comment by joshuajon** [comment]
Thanks for that explanation.  I'll check out @TheBarret's docs, as well as try to figure out what's going on from the tooltips.  Unfortunately I can't seem to get it to run at this point, but I figure I'll put that in a separate thread.
