### ISSUE TITLE
Is CUDA a strict requirement?

### ISSUE THREAD

**Issue by G3Kappa** [chrxh/alien#9]
Does this mean I'm left out if I have an AMD card? Can it fallback to OpenCL/CPU?

**Comment by chrxh** [comment]
Since only the CUDA api is currently used, unfortunately yes.
To overcome this problem, a platform-independent frontend is being developed at [github.com/chrxh/alien-world-explorer](https://github.com/chrxh/alien-world-explorer). 
A deployed version can be accessed [here](https://alien-project.org/world-explorer) for testing purposes (but still missing most features).

**Comment by G3Kappa** [comment]
Great, thank you! This project is really interesting. I'll keep an eye on it.
